---
title: "PG scoring of ADNI data based on IGAP results"
author: "Nathalie Nilsson"
date: "November 21, 2019"
output: 
  html_document: 
    df_print: kable
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Project
```{r}
basename(rprojroot::find_rstudio_root_file())
```

### Working directory relative to project
```{r}
gsub(rprojroot::find_rstudio_root_file(), "", getwd())
```

### Input
```{r}
# Target data
target.file         <- "D:/OneDrive - McGill University/Lab_stuff/Research/Cohort_data/ADNI_all/Genetic_data/ADNI-WGS/2018-01-30_qc/PCA_1kG_v3_LD/PCA_EUR/ADNI-WGS_EUR" # .bed; .bim & .fam file

# Base data
base.file           <- "D:/OneDrive - McGill University/Lab_stuff/Research/Collaborations/JV/AD_pathway/data/igap/ADNI-WGS_match_v3/ADNI-WGS_match_v3.txt" # summary file with header
base.file.snps.clump <- "D:/OneDrive - McGill University/Lab_stuff/Research/Collaborations/JV/AD_pathway/data/igap/ADNI-WGS_match_v3/ADNI-WGS_match_v3_SNPsClump.txt"
base.file.flip.snps <- "D:/OneDrive - McGill University/Lab_stuff/Research/Collaborations/JV/AD_pathway/data/igap/ADNI-WGS_match_v3/ADNI-WGS_match_v3_SNPsFlip.txt" # file with SNPs to flip
base.file.name      <- "igap"
base.file.cols 	    <- c(1, 2, 3, 4) # column numbers for SNP, A1, P and BETA
base.file.ps	    <- c(1e-8, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 0.05, 0.1, 0.5, 1)

# Clumping parameters
clump.p1 <- 1 # index variant p-value threshold
clump.p2 <- 1 # clumped variant p-value threshold
clump.kb <- 1000 # clump kb radius
clump.r2 <- 0.5 # r^2 threshold

# Output parameters
output.name 	<- "adni_pgs"

# Plink path
plink.file <- "C:/Program Files/Plink/plink.exe"

```

### Libraries
```{r}
library(tidyverse)
```

### Set up directory for analysis
```{r}
dir.create("target_files", recursive = TRUE)
dir.create("score_files")

file.copy(base.file, "base_file.txt")
file.copy(base.file.flip.snps, "snps_flip.txt")
file.copy(base.file.snps.clump, "snps_clump.txt")

file.copy(plink.file, "plink.exe")
```

### Pruning of data
```{r}
system(paste("plink --bfile \"", target.file, "\" --extract base_file.txt --make-bed --out temp", sep = ""))
cat(readLines("temp.log"), sep = "\n")

system(paste("plink --bfile temp --clump snps_clump.txt --clump-p1 ", clump.p1, " --clump-p2 ", clump.p2, " --clump-kb ", clump.kb, " --clump-r2 ", clump.r2, " --out target_files/", output.name, "_clump", sep = ""))
cat(readLines(paste("target_files/", output.name, "_clump.log", sep = "")), sep = "\n")

clumped <- read.table(paste("target_files/", output.name, "_clump.clumped", sep = ""), header = TRUE)

snps.incl <- clumped$SNP %>%
    unlist() %>%
    as.character()
write.table(data.frame(snps.incl), 
            file = paste("target_files/", output.name, "_inclSNPs.txt", sep = ""), 
            col.names = FALSE, row.names = FALSE, quote = FALSE)

system(paste("plink --bfile \"", target.file, "\" --extract target_files/", output.name, "_inclSNPs.txt --make-bed --out target_files/", output.name, "_LDPRUNED", sep = ""))
cat(readLines(paste("target_files/", output.name, "_LDPRUNED.log", sep = "")), sep = "\n")

```

### Range file
Creates a range file with the p cut-offs
```{r}
my.range.list <- cbind(label = c(paste("S0", 1:9, sep = ""), paste("S", 10:length(base.file.ps), sep = "")),
                       pmin = rep(0, length(base.file.ps)),
                       pmax = base.file.ps)
write.table(my.range.list, file = paste("scoring_range.txt", sep = ""), 
            row.names = FALSE, quote = FALSE, sep = "\t")
```

### Scoring
```{r}
system(paste("plink --bfile target_files/", output.name, "_LDPRUNED --flip snps_flip.txt --q-score-range scoring_range.txt base_file.txt 1 3 header --score base_file.txt 1 2 4 header --out score_files/", output.name, sep = ""))
cat(readLines(paste("score_files/", output.name, ".log", sep = "")), sep = "\n")

```

```{r}
file.remove("base_file.txt", "plink.exe", 'temp.bim', "temp.bed", "temp.fam")
```

